@startuml
Alice -> Bob: Authentication Request
Bob -> nginx: delegate
nginx -> Bob: response
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml